/**
 * Kitoblar ro'yxati. Yangi qo'llanma qo'shish uchun shu massivga bitta blok qo'shiladi —
 * qolgan hamma narsa (sidebar, marshrutlar, qidiruv, versiya, sana) avtomatik quriladi.
 */
export const contentRoot = process.env.DOCS_SOURCE ?? 'content'

export const books = [
  {
    id: 'symfony',
    title: 'Symfony',
    subtitle: 'HTTP, Doctrine, API va deploy',
    dir: 'symfony',
    logo: 'symfony',
    // Symfony logosi qora/oq; havolalar — symfony.com --link-color (blue-600 / blue-300)
    accent: '#000000',
    accentDark: '#ffffff',
    accentText: '#2563eb',
    accentTextDark: '#93c5fd',
    versionLabel: 'Symfony',
    versionRow: /^\|\s*Symfony\s*\|\s*([^|]+)\|/m,
    groups: [
      { title: 'I — Poydevor', from: 1, to: 8 },
      { title: 'II — HTTP qatlami', from: 9, to: 14 },
      { title: 'III — Ma\'lumotlar bazasi', from: 15, to: 19 },
      { title: 'IV — API qurish', from: 20, to: 24 },
      { title: 'V — Fon ishlari va xizmatlar', from: 25, to: 29 },
      { title: 'VI — Sifat va yakun', from: 30, to: 34 },
      { title: 'VII — Production darajasi', from: 35, to: 40 },
    ],
    folders: [
      { dir: 'patterns', title: 'Pattern katalogi' },
    ],
  },
  {
    id: 'laravel',
    title: 'Laravel',
    subtitle: 'Symfony dasturchilari uchun',
    dir: 'laravel',
    logo: 'laravel',
    // Laravel logomark #FF2D20; havolalar — laravel.com --color-laravel-red-darkened
    accent: '#ff2d20',
    accentDark: '#ff2d20',
    accentText: '#c42602',
    versionLabel: 'Laravel',
    versionRow: /^\|\s*Laravel Framework\s*\|\s*([^|]+)\|/m,
    groups: [
      { title: 'I — Poydevor', from: 1, to: 8 },
      { title: 'II — HTTP qatlami', from: 9, to: 13 },
      { title: 'III — Ma\'lumotlar bazasi', from: 14, to: 19 },
      { title: 'IV — API qurish', from: 20, to: 23 },
      { title: 'V — Fon ishlari va xizmatlar', from: 24, to: 28 },
      { title: 'VI — Sifat va yakun', from: 29, to: 34 },
    ],
    folders: [],
  },
  {
    id: 'vue',
    title: 'Vue',
    subtitle: 'reaktivlik, komponentlar, Pinia va Nuxt',
    dir: 'vue',
    logo: 'vue',
    // Vue brend yashili #42B883; havolalar — vuejs.org --vt-c-green-darker (oq fonda o'qilishi uchun)
    accent: '#42b883',
    accentDark: '#42b883',
    accentText: '#155f3e',
    versionLabel: 'Vue',
    versionRow: /^\|\s*Vue\s*\|\s*([^|]+)\|/m,
    // Options / Composition API almashtirgichi shu kitobda ko'rinadi
    variants: {
      group: 'api',
      label: 'API uslubi',
      options: [
        { value: 'composition', label: 'Composition', title: 'Composition API: <script setup> + ref/computed' },
        { value: 'options', label: 'Options', title: 'Options API: export default { data, methods }' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 7 },
      { title: 'II — Shablon va reaktivlik', from: 8, to: 17 },
      { title: 'III — Komponentlar', from: 18, to: 28 },
      { title: 'IV — Qayta ishlatish va ichki komponentlar', from: 29, to: 36 },
      { title: 'V — Ilova miqyosi', from: 37, to: 47 },
      { title: 'VI — TypeScript', from: 48, to: 50 },
      { title: 'VII — Sifat va testlash', from: 51, to: 55 },
      { title: 'VIII — SSR, Nuxt va SEO', from: 56, to: 61 },
      { title: 'IX — Production darajasi', from: 62, to: 70 },
    ],
    folders: [],
  },
  {
    id: 'react',
    title: 'React',
    subtitle: 'hooklar, holat va ilova arxitekturasi',
    dir: 'react',
    logo: 'react',
    // react.dev: logo #58C4DC, yorug' rejimdagi havola #087EA4
    accent: '#58c4dc',
    accentDark: '#58c4dc',
    accentText: '#087ea4',
    versionLabel: 'React',
    versionRow: /^\|\s*React\s*\|\s*([^|]+)\|/m,
    variants: {
      group: 'lang',
      label: 'Kod tili',
      options: [
        { value: 'ts', label: 'TypeScript', title: 'TypeScript bilan (tavsiya etiladi)' },
        { value: 'js', label: 'JavaScript', title: 'Oddiy JavaScript bilan' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 7 },
      { title: 'II — JSX va komponentlar', from: 8, to: 15 },
      { title: 'III — Holat va hooklar', from: 16, to: 26 },
      { title: 'IV — Effektlar va tashqi dunyo', from: 27, to: 33 },
      { title: 'V — Ilova arxitekturasi', from: 34, to: 42 },
      { title: 'VI — Sifat va production', from: 43, to: 50 },
    ],
    folders: [],
  },
  {
    id: 'nextjs',
    title: 'Next.js',
    subtitle: 'App Router, RSC, auth va deploy',
    dir: 'nextjs',
    logo: 'nextjs',
    // Next.js logosi qora/oq; havolalar — nextjs.org ko'k (ds-blue-900)
    accent: '#000000',
    accentDark: '#ffffff',
    accentText: '#0068d6',
    accentTextDark: '#52a8ff',
    versionLabel: 'Next.js',
    versionRow: /^\|\s*Next\.js\s*\|\s*([^|]+)\|/m,
    variants: {
      group: 'lang',
      label: 'Kod tili',
      options: [
        { value: 'ts', label: 'TypeScript', title: 'TypeScript bilan (tavsiya etiladi)' },
        { value: 'js', label: 'JavaScript', title: 'Oddiy JavaScript bilan' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 6 },
      { title: 'II — App Router', from: 7, to: 15 },
      { title: 'III — Server komponentlar va ma\'lumot', from: 16, to: 24 },
      { title: 'IV — Auth va tokenlar', from: 25, to: 31 },
      { title: 'V — Ma\'lumotlar bazasi va integratsiyalar', from: 32, to: 37 },
      { title: 'VI — Pages Router va migratsiya', from: 38, to: 41 },
      { title: 'VII — Sifat va production', from: 42, to: 50 },
    ],
    folders: [],
  },
  {
    id: 'angular',
    title: 'Angular',
    subtitle: 'signallar, DI va production',
    dir: 'angular',
    logo: 'angular',
    // Rasmiy Angular logosi gradientining ranglari (#E40035 … #FF31D9)
    accent: '#e40035',
    accentDark: '#ff31d9',
    versionLabel: 'Angular',
    versionRow: /^\|\s*@angular\/core\s*\|\s*([^|]+)\|/m,
    groups: [
      { title: 'I — Poydevor', from: 1, to: 7 },
      { title: 'II — Shablon va boshqaruv oqimi', from: 8, to: 15 },
      { title: 'III — Signallar va reaktivlik', from: 16, to: 24 },
      { title: 'IV — Komponentlar chuqur', from: 25, to: 33 },
      { title: 'V — Dependency Injection', from: 34, to: 39 },
      { title: 'VI — Marshrutlash', from: 40, to: 46 },
      { title: 'VII — Formalar', from: 47, to: 54 },
      { title: 'VIII — HTTP, auth va holat', from: 55, to: 61 },
      { title: 'IX — SSR va hybrid rendering', from: 62, to: 65 },
      { title: 'X — Ekotizim', from: 66, to: 70 },
      { title: 'XI — Sifat va production', from: 71, to: 78 },
    ],
    folders: [],
  },
  {
    id: 'arxitektura',
    title: 'Arxitektura',
    subtitle: 'frontend va backend: chegaralar va kesishmalar',
    dir: 'arxitektura',
    logo: 'arxitektura',
    accent: '#5b4bd6',
    accentDark: '#a99bff',
    versionLabel: 'Arxitektura',
    // Bu kitob texnologiyaga bog'liq emas — versiya qatori yo'q
    groups: [
      { title: 'I — Arxitektura nima', from: 1, to: 7 },
      { title: 'II — Umumiy tamoyillar', from: 8, to: 18 },
      { title: 'III — Backend arxitekturasi', from: 19, to: 35 },
      { title: 'IV — Frontend arxitekturasi', from: 36, to: 52 },
      { title: 'V — Kesishma: shartnoma va integratsiya', from: 53, to: 67 },
      { title: 'VI — Ma\'lumot va integratsiya', from: 68, to: 74 },
      { title: 'VII — Sifat, ish va rivojlanish', from: 75, to: 84 },
      { title: 'VIII — AI davrida arxitektura', from: 85, to: 89 },
      { title: 'IX — Amaliyot', from: 90, to: 91 },
    ],
    folders: [],
  },
  {
    id: 'fsd',
    title: 'FSD',
    subtitle: 'Feature-Sliced Design: qoidalar va tayyor shablonlar',
    dir: 'fsd',
    logo: 'fsd',
    // FSD flat logo #3193FF, primary gradient #29BEDC; oq fonda matn — #3193FF'ning 20% to'qroq varianti (palitrada o'qiladigan rang yo'q)
    accent: '#3193ff',
    accentDark: '#29bedc',
    accentText: '#2776cc',
    versionLabel: 'FSD',
    versionRow: /^\|\s*Feature-Sliced Design\s*\|\s*([^|]+)\|/m,
    // Kod misollari bitta framework'da ko'rinadi — tanlov sidebar'da
    variants: {
      group: 'fw',
      label: 'Framework',
      options: [
        { value: 'react', label: 'React', title: 'React misollari' },
        { value: 'vue', label: 'Vue', title: 'Vue misollari' },
        { value: 'angular', label: 'Angular', title: 'Angular misollari' },
      ],
    },
    groups: [
      { title: 'I — Asoslar', from: 1, to: 6 },
      { title: 'II — Qatlamlar chuqur', from: 7, to: 13 },
      { title: 'III — Chegaralar va bog\'lanish', from: 14, to: 19 },
      { title: 'IV — Tipik vazifalar', from: 20, to: 26 },
      { title: 'V — Framework shablonlari', from: 27, to: 32 },
      { title: 'VI — Asboblar va jamoa', from: 33, to: 36 },
      { title: 'VII — Amaliyot', from: 37, to: 40 },
    ],
    folders: [],
  },
  {
    id: 'sql',
    title: 'SQL',
    subtitle: 'PostgreSQL: so\'rovlar, sxema va unumdorlik',
    dir: 'sql',
    logo: 'sql',
    // PostgreSQL logosi (postgres/pgweb) #336791; qorong'i fonda matn — #336791'ning ochroq varianti (palitrada yo'q)
    accent: '#336791',
    accentDark: '#699eca',
    versionLabel: 'PostgreSQL',
    groups: [
      { title: 'I — Poydevor', from: 1, to: 6 },
      { title: 'II — So\'rovlar', from: 7, to: 14 },
      { title: 'III — Sxema dizayni', from: 15, to: 20 },
      { title: 'IV — Unumdorlik', from: 21, to: 26 },
      { title: 'V — Tranzaksiyalar va parallellik', from: 27, to: 30 },
      { title: 'VI — Ishlab chiqarish', from: 31, to: 36 },
    ],
    folders: [],
  },
  {
    id: 'git',
    title: 'Git',
    subtitle: 'model, jamoaviy ish va tiklanish',
    dir: 'git',
    logo: 'git',
    // Git logosi (git/git-scm.com) #F03C2E; oq fonda matn — to'qroq variant (palitrada yo'q)
    accent: '#f03c2e',
    accentDark: '#f03c2e',
    accentText: '#c4271b',
    versionLabel: 'Git',
    groups: [
      { title: 'I — Asoslar', from: 1, to: 7 },
      { title: 'II — Branch\'lar', from: 8, to: 13 },
      { title: 'III — Masofaviy repo va jamoa', from: 14, to: 19 },
      { title: 'IV — Tiklanish va chuqur', from: 20, to: 24 },
    ],
    folders: [],
  },
  {
    id: 'docker',
    title: 'Docker',
    subtitle: 'konteynerlar, Compose va deploy',
    dir: 'docker',
    logo: 'docker',
    // Docker "ocean blue" logosi (docker.com media resources) #2560FF; qorong'i fonda matn — ochroq variant
    accent: '#2560ff',
    accentDark: '#6ea1ff',
    versionLabel: 'Docker',
    groups: [
      { title: 'I — Tushunchalar', from: 1, to: 6 },
      { title: 'II — Dockerfile', from: 7, to: 14 },
      { title: 'III — Docker Compose', from: 15, to: 20 },
      { title: 'IV — Framework\'lar uchun', from: 21, to: 24 },
      { title: 'V — Production', from: 25, to: 28 },
    ],
    folders: [],
  },
]
