/**
 * Kitoblar ro'yxati. Yangi qo'llanma qo'shish uchun shu massivga bitta blok qo'shiladi —
 * qolgan hamma narsa (sidebar, marshrutlar, qidiruv, versiya, sana) avtomatik quriladi.
 */
export const contentRoot = process.env.DOCS_SOURCE ?? 'content'

export const books = [
  {
    id: 'symfony',
    title: 'Symfony',
    subtitle: 'noldan production darajasigacha',
    dir: 'symfony',
    logo: 'symfony',
    accent: '#0b6e4f',
    accentDark: '#4cc79a',
    versionLabel: 'Symfony',
    versionRow: /^\|\s*Symfony\s*\|\s*([^|]+)\|/m,
    groups: [
      { title: 'I — Poydevor', from: 1, to: 8 },
      { title: 'II — HTTP qatlami', from: 9, to: 14 },
      { title: 'III — Ma\'lumotlar bazasi', from: 15, to: 19 },
      { title: 'IV — API qurish', from: 20, to: 24 },
      { title: 'V — Fon ishlari va xizmatlar', from: 25, to: 29 },
      { title: 'VI — Sifat va yakun', from: 30, to: 34 },
      { title: 'VII — Production darajasi', from: 35, to: 40 },
    ],
    folders: [
      { dir: 'patterns', title: 'Pattern katalogi' },
    ],
  },
  {
    id: 'laravel',
    title: 'Laravel',
    subtitle: 'Symfony dasturchilari uchun',
    dir: 'laravel',
    logo: 'laravel',
    accent: '#b5331f',
    accentDark: '#ff7a5c',
    versionLabel: 'Laravel',
    versionRow: /^\|\s*Laravel Framework\s*\|\s*([^|]+)\|/m,
    groups: [
      { title: 'I — Poydevor', from: 1, to: 8 },
      { title: 'II — HTTP qatlami', from: 9, to: 13 },
      { title: 'III — Ma\'lumotlar bazasi', from: 14, to: 19 },
      { title: 'IV — API qurish', from: 20, to: 23 },
      { title: 'V — Fon ishlari va xizmatlar', from: 24, to: 28 },
      { title: 'VI — Sifat va yakun', from: 29, to: 34 },
    ],
    folders: [],
  },
  {
    id: 'vue',
    title: 'Vue',
    subtitle: 'noldan senior darajasigacha',
    dir: 'vue',
    logo: 'vue',
    accent: '#35845f',
    accentDark: '#42d392',
    versionLabel: 'Vue',
    versionRow: /^\|\s*Vue\s*\|\s*([^|]+)\|/m,
    // Options / Composition API almashtirgichi shu kitobda ko'rinadi
    variants: {
      group: 'api',
      label: 'API uslubi',
      options: [
        { value: 'composition', label: 'Composition', title: 'Composition API: <script setup> + ref/computed' },
        { value: 'options', label: 'Options', title: 'Options API: export default { data, methods }' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 7 },
      { title: 'II — Shablon va reaktivlik', from: 8, to: 17 },
      { title: 'III — Komponentlar', from: 18, to: 28 },
      { title: 'IV — Qayta ishlatish va ichki komponentlar', from: 29, to: 36 },
      { title: 'V — Ilova miqyosi', from: 37, to: 47 },
      { title: 'VI — TypeScript', from: 48, to: 50 },
      { title: 'VII — Sifat va testlash', from: 51, to: 55 },
      { title: 'VIII — SSR, Nuxt va SEO', from: 56, to: 61 },
      { title: 'IX — Production darajasi', from: 62, to: 70 },
    ],
    folders: [],
  },
  {
    id: 'react',
    title: 'React',
    subtitle: 'noldan senior darajasigacha',
    dir: 'react',
    logo: 'react',
    accent: '#0b7fa0',
    accentDark: '#58c4dc',
    versionLabel: 'React',
    versionRow: /^\|\s*React\s*\|\s*([^|]+)\|/m,
    variants: {
      group: 'lang',
      label: 'Kod tili',
      options: [
        { value: 'ts', label: 'TypeScript', title: 'TypeScript bilan (tavsiya etiladi)' },
        { value: 'js', label: 'JavaScript', title: 'Oddiy JavaScript bilan' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 7 },
      { title: 'II — JSX va komponentlar', from: 8, to: 15 },
      { title: 'III — Holat va hooklar', from: 16, to: 26 },
      { title: 'IV — Effektlar va tashqi dunyo', from: 27, to: 33 },
      { title: 'V — Ilova arxitekturasi', from: 34, to: 42 },
      { title: 'VI — Sifat va production', from: 43, to: 50 },
    ],
    folders: [],
  },
  {
    id: 'nextjs',
    title: 'Next.js',
    subtitle: 'App Router, RSC va production',
    dir: 'nextjs',
    logo: 'nextjs',
    accent: '#1f2933',
    accentDark: '#e6e6e6',
    versionLabel: 'Next.js',
    versionRow: /^\|\s*Next\.js\s*\|\s*([^|]+)\|/m,
    variants: {
      group: 'lang',
      label: 'Kod tili',
      options: [
        { value: 'ts', label: 'TypeScript', title: 'TypeScript bilan (tavsiya etiladi)' },
        { value: 'js', label: 'JavaScript', title: 'Oddiy JavaScript bilan' },
      ],
    },
    groups: [
      { title: 'I — Poydevor', from: 1, to: 6 },
      { title: 'II — App Router', from: 7, to: 15 },
      { title: 'III — Server komponentlar va ma\'lumot', from: 16, to: 24 },
      { title: 'IV — Auth va tokenlar', from: 25, to: 31 },
      { title: 'V — Ma\'lumotlar bazasi va integratsiyalar', from: 32, to: 37 },
      { title: 'VI — Pages Router va migratsiya', from: 38, to: 41 },
      { title: 'VII — Sifat va production', from: 42, to: 50 },
    ],
    folders: [],
  },
  {
    id: 'arxitektura',
    title: 'Arxitektura',
    subtitle: 'frontend va backend: chegaralar va kesishmalar',
    dir: 'arxitektura',
    logo: 'arxitektura',
    accent: '#5b4bd6',
    accentDark: '#a99bff',
    versionLabel: 'Arxitektura',
    // Bu kitob texnologiyaga bog'liq emas — versiya qatori yo'q
    groups: [
      { title: 'I — Arxitektura nima', from: 1, to: 7 },
      { title: 'II — Umumiy tamoyillar', from: 8, to: 16 },
      { title: 'III — Backend arxitekturasi', from: 17, to: 30 },
      { title: 'IV — Frontend arxitekturasi', from: 31, to: 43 },
      { title: 'V — Kesishma: shartnoma va integratsiya', from: 44, to: 56 },
      { title: 'VI — Ma\'lumot va integratsiya', from: 57, to: 62 },
      { title: 'VII — Sifat, ish va rivojlanish', from: 63, to: 72 },
    ],
    folders: [],
  },
]
